[connections.snowflake]
account = "SNRUMVF.TW78850"
user = "rbourges"
password = "qiThE1$zegudapHLfreBa1H0craFri"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
